#!/bin/bash

HOST="zeus"
STANDUP_FILE="standup.txt"
BACKUP_FILE="standup-prev.txt"
VIM_COMMANDS="+'setf slack' +'set spell' +'set wrap'"

case "$1" in
  -l|--local)
    HOST=zeus
    ;;
  -r|--remote)
    HOST=cerberus
    ;;
esac

standup_line_count="$( ssh $HOST -- cat $STANDUP_FILE | wc -l )"

if [[ $standup_line_count -gt 0 ]]; then
  exec vim -o \
    "scp://$HOST/$STANDUP_FILE" \
    "scp://$HOST/$BACKUP_FILE" \
    "$VIM_COMMANDS"
else
  exec vim \
    "scp://$HOST/$STANDUP_FILE" \
    +"r scp://$HOST/$BACKUP_FILE" \
    +0d \
    "$VIM_COMMANDS"
fi
