#!/bin/bash

HOST="zeus"
STANDUP_FILE="standup.txt"
BACKUP_FILE="standup-prev.txt"

case "$1" in
  -l|--local)
    HOST=zeus
    ;;
  -r|--remote)
    HOST=cerberus
    ;;
esac

standup_line_count="$( ssh $HOST -- cat $STANDUP_FILE | wc -l )"

if [[ $standup_line_count -gt 0 ]]; then
  exec vim -o \
    "scp://$HOST/$STANDUP_FILE" \
    "scp://$HOST/$BACKUP_FILE" \
    "+bufdo setlocal filetype=slack wrap spell" \
    "+b1" \
    "+syn on"
else
  exec vim \
    "scp://$HOST/$STANDUP_FILE" \
    "+r scp://$HOST/$BACKUP_FILE" \
    "+0d" \
    "+set filetype=slack wrap spell"
fi
